package com.vctek.orderservice.excel;

public enum RowMapperErrorCodes {
    EMPTY_SKU,
    INVALID_QUANTITY,
    INVALID_DISCOUNT,
    INVALID_DISCOUNT_TYPE,
    INVALID_PRICE,
    PRODUCT_HAS_NOT_PRICE,
    INVALID_PRODUCT_SKU,
    PRODUCT_HAS_NOT_WHOLESALE_PRICE,
    INVALID_COMBO,
    RETAIL_PRICE_MUST_BE_LARGE_WHOLESALE_PRICE,
    INVALID_COMBO_PRICE_LESS_THAN,
    INVALID_COMBO_PRICE_LARGER_THAN,
    MUST_LAGRE_MORE,
    WRONG_DISCOUNT_FORMAT,
    EMPTY_DISCOUNT_TYPE,
    WRONG_FORMAT,
    INVALID_DISTRIBUTOR_ID,
    NOT_ACCEPTED_BASE_PRODUCT,
    NOT_ALLOW_SELL,
    STOP_SELLING
    ;
}
